from .combat.combat import OSRSCombat
from .woodcutter import OSRSWoodcutter
from .WillowsDad.WDCombat import OSRSWDCombat
from .WillowsDad.WDWoodcutting import OSRSWDWoodcutting
from .WillowsDad.WDUltraCompost import OSRSWDUltraCompostMaker
from .WillowsDad.WDDegrimer import OSRSWDDegrimer
from .WillowsDad.WDFishing import OSRSWDFishing
from .WillowsDad.WillowsDad_bot import WillowsDadBot
from .WillowsDad.WDMining import OSRSWDMining
from .Bow_Fletcher.BowFletcher import OSRSBowFletcher
from .new_pickpocket import NewPickPocket
from .smithing import Furnace